manual_director_owners:
- user_id: 70
  directors:
  - ЖИЛКАШИНОВА АСЕЛЬ МИХАЙЛОВНА
  - ЖЫЛКАШИНОВА АСЕЛЬ МИХАЙЛОВНА
  - АСЕЛЬ ЖИЛКАШИНОВА
  - АСЕЛЬ ЖЫЛКАШИНОВА
- user_id: 78
  directors:
  - ТАТАЕВ НУРЛАН САПАРАЛИЕВИЧ
  - ТАТАЕВ НУРЛАН
- user_id: 102
  directors:
  - МЯО ЮН
  - МАО ЮН
  - БОЦМАН ВИКТОР ВАЛЕРЬЕВИЧ
  - БОЦМАН ВИКТОР
- user_id: 74
  directors:
  - КАЛКУЛОВ НУРСУЛТАН КЕРИМБАЕВИЧ
  - КАЛКУЛОВ НУРСУЛТАН
  - КАЛКУЛОВ НУРССУЛТАН
  - КАЛКУЛОВ НУРССУЛТАН КЕРИМБАЕВИЧ
  - САМАРИНА НАДЕЖДА АЛЕКСЕЕВНА
  - ДЖЕНАЛИНОВА МАДИНА ЖАНАТЛЕКОВНА
- user_id: 72
  directors:
  - МУКУШЕВ АРДАК БОЛАТОВИЧ
  - МУКУШЕВ АРДАК
  - КУДИН АЛЕКСЕЙ АЛЕКСАНДРОВИЧ
